"use client";
import { Open_Sans } from "next/font/google";

import "./globals.scss";
import MobileView from "components/mobile";
import Header from "components/header";
import "styles";
import Sidebar from "components/sidebar";
import Container from "components/container";
import StyledComponentsRegistry from "../lib/AntdRegistry";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLoggedIn = true;

  const getComponent = () => {
    if (!isLoggedIn) return children;
    return (
      <main className={"container"}>
        <Sidebar />
        <Container>{children}</Container>
      </main>
    );
  };

  return (
    <html lang="en">
      <body className={openSans.className}>
        <StyledComponentsRegistry>{getComponent()}</StyledComponentsRegistry>
      </body>
    </html>
  );
}

// var isMobile = window?.innerWidth < 576;
// var isMobile = false;

// window.addEventListener("resize", () => window.location.reload());

// const getChildren = () => {
//   return <>
//     <main>
//       {/* <Header /> */}
//       {children}
//     </main>
//   </>
// }
// {/* {isMobile ? <MobileView>
//           {getChildren()}
//         </MobileView> :
//           getChildren()
//         } */}
